# Generated by Django 5.2.3 on 2025-06-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
