# Generated by Django 5.2.3 on 2025-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_jobposting_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/company_logos/'),
        ),
    ]
