# Generated by Django 5.2.3 on 2025-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_alter_jobposting_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
